# Generated by Django 4.1 on 2022-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rename_status_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
